baseurl      = "https://localhost"
title        = "My Blog"
languageCode = "en-us"
theme        = "hello-friend-ng"




archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpired = false
canonifyURLs = false

enableInlineShortcodes = true
enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[permalinks]
  posts = "/posts/:year/:month/:title/"

[author]
  name = "Echo Rex"

[blackfriday]
  hrefTargetBlank = true
[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Subtitle for home
  homeSubtitle = "Don't worry , Be happy!"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"

  # Default theme "light" or "dark"
  defaultTheme = "dark"
  [params.favicon.color]
    mask = "#252627"
    msapplication = "#252627"
    theme = "#252627"
  # [[params.social]]
  #   name = "twitter"
  #   url  = "https://twitter.com/"

  # [[params.social]]
  #   name = "email"
  #   url  = "xxiao_l@163.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/min-zou"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/"

  [[params.social]]
    name = "stackoverflow"
    url  = "https://www.stackoverflow.com/"


[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Hello World"
    subtitle = "test"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "GoooooÔºÅ"
      # logoHomeLink = "https://www.robot-rex.top"
      logoHomeLink = "https://min-zou.github.io/record.github.io"

    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "icon-list"
    # name       = "Record"
    weight = 20
    pre = "<i class='fa fa-road'></i>"
    url        = "/posts"
  [[menu.main]]
    identifier = "icon-about"
    # name       = "about"
    url        = "/about_me"
  [[menu.main]]
    identifier = "icon-ref"
    # name       = "Refrence"
    url        = "/refs"
  [[menu.main]]
    identifier = "icon-fun"
    # name       = "Fun"
    url        = "/extra"